from odoo import models, fields

class ModelEmployee(models.Model):
    _inherit = 'hr.employee'

    employee_id_number = fields.Integer(string='Employee ID Number', required=True)
    salutation = fields.Char(string='Salutation', size=10)
    # full_name = fields.Char(string='Full Name', size=100)
    # place_of_birth = fields.Char(string='Place of Birth', size=50)
    # date_of_birth = fields.Date(string='Date of Birth')
    mother_maiden_name = fields.Char(string='Mother Maiden Name', size=100)
    # gender = fields.Char(string='Gender', size=10)
    religion = fields.Char(string='Religion', size=50)
    blood_type = fields.Char(string='Blood Type', size=5)
    # nationality = fields.Char(string='Nationality', size=50)
    # marital_status = fields.Char(string='Marital Status', size=20)
    number_of_children = fields.Integer(string='Number of Children')
    last_education = fields.Char(string='Last Education', size=100)
    major = fields.Char(string='Major', size=100)
    bpjs_tk_npp = fields.Char(string='BPJS TK NPP', size=20)
    bpjs_healthcare_npp = fields.Char(string='BPJS Healthcare NPP', size=20)
    id_information_id_type = fields.Char(string='ID Information ID Type', size=20)
    id_information_id_number = fields.Char(string='ID Information ID Number', size=50)
    tax_id_number = fields.Char(string='Tax ID Number', size=50)
    tax_effective_date = fields.Date(string='Tax Effective Date')
    tax_revoke_date = fields.Date(string='Tax Revoke Date')
    tax_status_status = fields.Char(string='Tax Status Status', size=20)
    employee_tax_policy = fields.Char(string='Employee Tax Policy', size=100)
    previous_net_income = fields.Float(string='Previous Net Income', digits=(10, 2))
    previous_tax_paid = fields.Float(string='Previous Tax Paid', digits=(10, 2))
    payslip_distribution = fields.Char(string='Payslip Distribution', size=50)
    user_name = fields.Char(string='User Name', size=50)
    password = fields.Char(string='Password', size=100)
    legal_address_address = fields.Char(string='Legal Address Address', size=200)
    legal_address_regency_city = fields.Char(string='Legal Address Regency/City', size=100)
    legal_address_district = fields.Char(string='Legal Address District', size=100)
    legal_address_village = fields.Char(string='Legal Address Village', size=100)
    legal_address_province = fields.Char(string='Legal Address Province', size=100)
    legal_address_country = fields.Char(string='Legal Address Country', size=100)
    legal_address_post_code = fields.Char(string='Legal Address Post Code', size=20)
    permanent_address_is_the_same_as_legal_address = fields.Boolean(string='Permanent Address is the same as Legal Address')
    permanent_address_address = fields.Char(string='Permanent Address Address', size=200)
    permanent_address_regency_city = fields.Char(string='Permanent Address Regency/City', size=100)
    permanent_address_district = fields.Char(string='Permanent Address District', size=100)
    permanent_address_village = fields.Char(string='Permanent Address Village', size=100)
    permanent_address_province = fields.Char(string='Permanent Address Province', size=100)
    permanent_address_country = fields.Char(string='Permanent Address Country', size=100)
    permanent_address_post_code = fields.Char(string='Permanent Address Post Code', size=20)
    mailing_address_is_the_same_as_legal_address = fields.Boolean(string='Mailing Address is the same as Legal Address')
    mailing_address_is_the_same_as_permanent_address = fields.Boolean(string='Mailing Address is the same as Permanent Address')
    mailing_address_address = fields.Char(string='Mailing Address Address', size=200)
    mailing_address_regency_city = fields.Char(string='Mailing Address Regency/City', size=100)
    mailing_address_district = fields.Char(string='Mailing Address District', size=100)
    mailing_address_village = fields.Char(string='Mailing Address Village', size=100)
    mailing_address_province = fields.Char(string='Mailing Address Province', size=100)
    mailing_address_country = fields.Char(string='Mailing Address Country', size=100)
    mailing_address_post_code = fields.Char(string='Mailing Address Post Code', size=20)
    residential_phone_number = fields.Char(string='Residential Phone Number', size=20)
    office_phone_number = fields.Char(string='Office Phone Number', size=20)
    mobile_phone_number = fields.Char(string='Mobile Phone Number', size=20)
    corporate_email_address = fields.Char(string='Corporate Email Address', size=100)
    personal_email_address = fields.Char(string='Personal Email Address', size=100)
    # date_of_hire = fields.Date(string='Date of Hire')
    # join_date = fields.Date(string='Join Date')
    status_information_employment_status = fields.Char(string='Status Information Employment Status', size=50)
    status_information_employee_status = fields.Char(string='Status Information Employee Status', size=50)
    # end_date_of_probation = fields.Date(string='End Date of Probation')
    # work_location = fields.Char(string='Work Location', size=100)
    contract_no = fields.Char(string='Contract No', size=50)
    # contract_start_date = fields.Date(string='Contract Start Date')
    # contract_end_date = fields.Date(string='Contract End Date')
    working_time_code = fields.Char(string='Working Time Code', size=20)
    position_code = fields.Char(string='Position Code', size=20)
    division_code = fields.Char(string='Division Code', size=20)
    department_code = fields.Char(string='Department Code', size=20)
    grade_code = fields.Char(string='Grade Code', size=20)
    cost_center = fields.Char(string='Cost Center', size=50)
    deputation = fields.Char(string='Deputation', size=50)
    payment_type = fields.Char(string='Payment Type', size=50)
    payment_from_bank_account = fields.Char(string='Payment from Bank Account', size=50)
    employee_account_no = fields.Char(string='Employee Account No', size=50)
    employee_bank = fields.Char(string='Employee Bank', size=100)
    employee_bank_branch = fields.Char(string='Employee Bank Branch', size=100)
    employee_currency_code = fields.Char(string='Employee Currency Code', size=5)
    employee_account_name = fields.Char(string='Employee Account Name', size=100)
